version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: instagram
    container_name: server
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=dbinstagram
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - '3000:3000'
    links:
      - dbinstagram
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/ap/node_modules
    networks:
      - app-network
  dbinstagram:
    container_name: dbinstagram
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    ports:
      - '27018:27017'
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
