swagger: '2.0'

info:
  version: 1.0
  title: Instagram API
  description: A instagram API

schemes:
  - https
host: localhost
basePath: /api

paths:
  /comments:
    get:
      summary: Get comments from user id
      description: Return a list of comments
      parameters: :id
      responses:
        200:
          description: A list of Person
          schema:
            type: array
            items:
              required:
                - username
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                username:
                  type: string
        404:
          schema:
            type: object
            items:
